In [ ]:
# Question - 1
import numpy as np
a=int(input("First number : "))
c=int(input("last number : "))
array1 = np.arange(a, c+1, 1)
print("Original array:",array1)
b = 5
array2 = np.zeros(len(array1) + (len(array1)-1)*(b))
array2[::b+19] = array1
print("\nNew array:"," ",array2)

First number : 10
last number : 14
Original array: [10 11 12 13 14]

New array:   [10.  0.  0.  0.  0.  0. 11.  0.  0.  0.  0.  0. 12.  0.  0.  0.  0.  0.
 13.  0.  0.  0.  0.  0. 14.]


In [ ]:
# Question - 2
import numpy as np

array1 = []
a = int(input("Size of array:"))
for i in range(a):
    array1.append(float(input("Element:")))
array1 = np.array(array1)
print(np.floor(array1))

array2=[]
b = int(input("Size of array:"))
for i in range(b):
    array2.append(float(input("Element:")))
array2 = np.array(array2)
print(np.floor(array2))
print()

print(np.array_equal(array1,array2))

Size of array:4
Element:5
Element:4
Element:3
Element:1
[5. 4. 3. 1.]
Size of array:4
Element:6
Element:4
Element:3
Element:1
[6. 4. 3. 1.]
False


In [ ]:
# Question -3 
import numpy as np
print(0 * np.nan)
print(np.nan != np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1) 

nan
True
False
nan
False


In [10]:
# Question - 4
import pandas as pd
ser = pd.Series(['amrita', 'school', 'of', 'engineering' 'chennai' , 'campus'])
ser= ser.str.capitalize()
print(ser)

0                Amrita
1                School
2                    Of
3    Engineeringchennai
4                Campus
dtype: object


In [12]:
# Question - 5
# Addition of Arrays    
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

print (" array1 : ", array1)
print (" array2 : ", array2)
	
add = np.add(array1, array2)
print (" addition of two arrays : ", add,"\n")



 array1 :  [1 2 3 4]
 array2 :  [5 6 7 8]
 addition of two arrays :  [ 6  8 10 12] 



In [13]:
# Multiplying a matrix
import numpy as np
# two dimensional arrays
matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.array([[7,8],[9,0],[5,6]])
matrix = np.dot(matrix1,matrix2) 
print(matrix) 

[[ 40  26]
 [103  68]]
